server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
          ### Client - http://localhost:4004/auth/login
          ### Auth-Service route - http://auth-service:4005/login

        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1  # After / it will strip 1, i.e., /api will be removed
          ### Client - http://localhost:4004/api/patients
          ### Patient-Service route - http://patient-service:4000/patients

        - id: api-patient-service-docs
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients/**
          filters:
            - RewritePath=/api-docs/patients, /v3/api-docs